apiVersion: v1
kind: Service
metadata:
  name: gdp-frontend-service
  namespace: gdp
spec:
  selector:
    pod: gdp-frontend-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP